server:
    forward-headers-strategy: native
    servlet:
        context-path:
        session:
            timeout: 60s

spring:
    application:
        name: oauth-resource-server
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://${spring.datasource.database.host}:${spring.datasource.database.port}/${spring.datasource.database.name}
    jpa:
        hibernate:
            ddl-auto: validate
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDB103Dialect
                jdbc.lob.non_contextual_creation: true
        show-sql: false

logging:
    level:
        root: WARN
        com.github.oauth.resource.server: DEBUG
        org.springframework.web: INFO
        org.springframework.security: INFO
        org.springframework.security.oauth2: INFO

security:
    oauth2:
        resource:
            jwk:
                key-set-uri: http://localhost:8183/oauth/access/token/jwk